DROP TABLE IF EXISTS hajok;

CREATE TABLE hajok (
    az INT NOT NULL AUTO_INCREMENT,
    nev VARCHAR(100) NOT NULL,
    tipus VARCHAR(50) NOT NULL,
    tulaz INT NULL,
    uzemel BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (az)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_hungarian_ci;

INSERT INTO hajok (az, nev, tipus, tulaz, uzemel) VALUES
(15, 'Ederics', 'személyhajó', 1, TRUE),
(77, 'Épvízkör 4', 'uszály', 5, TRUE),
(53, 'Nemere II.', 'vitorlás', NULL, TRUE),
(3, '101-Z toló-önjáró uszály', 'önjáró uszály', 2, TRUE),
(20, 'Hableány', 'személyhajó', 6, TRUE),
(4, 'Almádi', 'személyhajó', 1, TRUE),
(91, 'Szemes', 'személyhajó', 1, FALSE),
(52, 'Katamarán', 'vitorlás', 9, TRUE),
(11, 'Csiga-Biga', 'kisgéphajó', 4, TRUE),
(69, '465 uszály', 'uszály', 1, TRUE),
(46, 'VI-736-Z önjáró tankuszály', 'önjáró uszály', 8, TRUE),
(54, 'Öszöd', 'vitorlás', 12, TRUE),
(88, 'Földvár', 'személyhajó', 1, FALSE),
(35, 'Sió', 'szolgálati hajó', 1, TRUE),
(73, 'Óriás uszály', 'uszály', 2, TRUE),
(12, 'Csobánc', 'személyhajó', 1, TRUE),
(55, 'Phoenix', 'vitorlás', 13, TRUE),
(18, 'Füred', 'személyhajó', 1, TRUE),
(66, '442 uszály', 'uszály', 1, TRUE),
(21, 'Helka', 'személyhajó', 1, TRUE),
(42, 'Tátika', 'személyhajó', 9, TRUE),
(14, 'Echo', 'szolgálati hajó', 2, TRUE),
(17, 'Fonyód', 'személyhajó', 1, TRUE),
(59, 'Talizmán', 'vitorlás', 14, TRUE),
(72, '107 uszály', 'uszály', NULL, TRUE),
(44, 'Tünde', 'személyhajó', 1, TRUE),
(67, '443 uszály', 'uszály', 1, TRUE),
(34, 'Révfülöp', 'személyhajó', 1, TRUE),
(76, 'Épvízkör 3', 'uszály', 5, TRUE),
(43, 'Thetis', 'kisgéphajó', 10, TRUE),
(36, 'Siófok', 'személyhajó', 1, TRUE),
(22, 'Hévíz', 'személyhajó', 1, TRUE),
(79, '254 strandhomokozó', 'úszó munkagép', 1, TRUE),
(33, 'Scharnebeck', 'szolgálati hajó', 7, TRUE),
(65, '102-Z bárka', 'uszály', 2, TRUE),
(70, 'Óriás 469 uszály', 'uszály', 2, TRUE),
(40, 'Szent Miklós', 'személyhajó', 1, TRUE),
(31, 'Kossuth Lajos', 'komp', 1, TRUE),
(83, 'Beloiannisz', 'személyhajó', 1, FALSE),
(25, 'Jókai', 'személyhajó', 3, TRUE),
(89, 'Csopak', 'személyhajó', 1, FALSE),
(45, 'Tündér', 'kisgéphajó', 11, TRUE),
(61, 'Balatonboglár', 'halászhajó', 15, TRUE),
(50, 'Zánka', 'személyhajó', 9, TRUE),
(39, 'Széchenyi István', 'komp', 1, TRUE),
(1, 'Baross Gábor', 'komp', 1, TRUE),
(10, 'Calypso', 'kisgéphajó', 1, TRUE),
(48, 'Z-424 önjáró uszály', 'önjáró uszály', 1, TRUE),
(47, 'Vízvédelem', 'szolgálati hajó', 8, TRUE),
(6, 'Arács', 'személyhajó', 1, TRUE),
(38, 'Szántód', 'személyhajó', 1, TRUE),
(27, 'Keszthely', 'személyhajó', 1, TRUE),
(81, 'Szerhajó', 'úszó munkagép', 1, TRUE),
(26, 'Kelén', 'személyhajó', 1, TRUE),
(37, 'St Benedek', 'személyhajó', 4, TRUE),
(7, 'Badacsony', 'személyhajó', 1, TRUE),
(74, '51 uszály', 'uszály', 1, TRUE),
(68, '463 uszály', 'uszály', 1, TRUE),
(56, 'Sirocco', 'vitorlás', NULL, TRUE),
(93, 'Balaton II.', 'személyhajó', 7, FALSE),
(86, 'Szárszó', 'személyhajó', 1, FALSE),
(2, 'Akali', 'személyhajó', 1, TRUE),
(84, 'Gulács', 'személyhajó', 1, FALSE),
(13, 'Csongor', 'személyhajó', 1, TRUE),
(75, 'Góliát', 'uszály', 2, TRUE),
(41, 'Szikra', 'szolgálati hajó', 8, TRUE),
(82, 'Radzeer', 'kisgéphajó', NULL, FALSE),
(71, '103 uszály', 'uszály', 5, TRUE),
(30, 'Koloska', 'kisgéphajó', NULL, TRUE),
(60, 'Róza', 'vitorlás', 3, TRUE),
(29, 'Klára', 'személyhajó', 3, TRUE),
(58, 'Szaturnusz', 'vitorlás', 1, TRUE),
(62, 'Vonyarc', 'halászhajó', 15, TRUE),
(24, 'Jégmadár', 'szolgálati hajó', 2, TRUE),
(63, 'Busa', 'halászhajó', 15, TRUE),
(64, 'Angolna', 'halászhajó', 15, TRUE),
(32, 'Lelle', 'személyhajó', 1, TRUE),
(87, 'Tihany II', 'személyhajó', 1, FALSE),
(90, 'Dörgicse', 'személyhajó', 1, FALSE),
(49, 'Z-426 önjáró uszály', 'önjáró uszály', 1, TRUE),
(51, 'Juditta', 'vitorlás', 10, TRUE),
(85, 'Bakony', 'személyhajó', 1, FALSE),
(9, 'Brutus', 'kisgéphajó', NULL, TRUE),
(57, 'Sissy hercegnő', 'vitorlás', 6, TRUE),
(80, '50-II úszódaru', 'úszó munkagép', 1, TRUE),
(28, 'Kisfaludy Sándor', 'komp', 1, TRUE),
(16, 'Érd', 'szolgálati hajó', 5, TRUE),
(8, 'Balaton', 'személyhajó', 3, TRUE),
(78, '211 elevátor', 'úszó munkagép', 1, TRUE),
(92, 'Kenese', 'személyhajó', 16, FALSE),
(23, 'Izsó', 'szolgálati hajó', 2, TRUE),
(5, 'Aqua Pannonia', 'személyhajó', 1, TRUE),
(19, 'Györök', 'személyhajó', 1, TRUE);

ALTER TABLE hajok AUTO_INCREMENT = 94;